# Generated by Django 3.1 on 2020-08-20 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FollowList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'follow_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('email', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('hashed_password', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('user_email', models.OneToOneField(db_column='user_email', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='carat_profile.users')),
                ('name', models.CharField(max_length=80)),
                ('profile_image', models.ImageField(upload_to='images/profile')),
                ('cover_image', models.ImageField(upload_to='images/profile')),
                ('about_me', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'profiles',
                'managed': False,
            },
        ),
    ]
